### ISSUE TITLE
Verification issue

### ISSUE THREAD

**Issue by benmdts** [dafny-lang/ide-vscode#326] opened 2022-12-23 16:34 UTC
Failing code
------------

```dafny

```

Steps to reproduce the issue
----------------------------

* Dafny version: 3.10.0.41215
* Dafny VSCode extension version: 3.0.0
* 

Expected behavior
-----------------
Run Program

Actual behavior
---------------
Waiting for free solvers

**Comment by MikaelMayer** [comment] 2022-12-23 18:18
Can you please provide us a sample program on which to run this issue?
I had it in the past too ("waiting for free solver"), but I can't reproduce it consistently. How frequently do you have this issue?

**Comment by benmdts** [comment] 2022-12-23 18:23
predicate ordered(a: seq<int>)      // in decreasing order
{
    forall i,j | 0 <= i < j < |a| :: a[i] >= a[j]
}

predicate is_min(e: int, m: multiset<int>)      // e is the minimum in m
{
    e in m && forall e' | e' in m :: e <= e'
}

 predicate perm(a: seq<int>, b: seq<int>) {
        multiset(a) == multiset(b)
}



/**
 * A priority queue of integer values, represented as an ordered array,
 * with minimal value at the end.  The capacity (length of the array) is
 * set initially but increases dynamically when needed. 
 */
class PriorityQueue {
    var elems : array<int>;     // elements in decreasing order
    var size : int;             // number of elements in the queue

    /**
     * Create a queue with initial capacity {n}
     */
    constructor (n: int)
        requires n > 0
        ensures ok()
        ensures abs() == multiset([])
        ensures fresh(elems)
    {
        this.elems := new int[n];
        this.size := 0;
    }

    /**
     * Abstraction: a queue is a multiset (bag) of its elements 
     */
    function abs(): multiset<int>
        requires ok()
        reads this, elems
        ensures forall e | e in elems[..size] :: e in abs()
        ensures |abs()| == size
    {
        multiset(elems[..size])
    }

    /**
     * Representation invariant
     */
    predicate ok()
    reads this, elems
    {
        this.size <= this.elems.Length && this.size >= 0 && ordered(elems[..size])
    }

    /**
     * Return the minimal element in the queue.  Does not modify the queue.
     */
    method peek_min() returns (m: int)
    requires ok()&&size>0
    ensures size==old(size)&&ok()&&is_min(m,abs())&&perm(elems[..],old(elems[..]))
    {
        return elems[size-1];
    }

    /**
     * Remove and return the minimal element in the queue.
     */
    method get_min() returns (m: int)
        requires ok()&&size>0
        modifies this
        ensures size==old(size)-1 &&ok()&&old(is_min(m,abs()))
    {
        m := elems[size-1];
        size := size - 1;
    }

    /**
     * Resize the queue to a larger capacity.  The content of the queue is preserved.
     */
    method resize()
        requires ok() && this.elems.Length>0
        ensures this.elems.Length==old(this.elems.Length)*2 && ok()&&size==old(size)
        modifies this
    {
        var len := elems.Length * 2;
        var newelems := new int[len];
        var i := 0;
        while i < size
            invariant i <= size
            invariant forall j | 0 <= j < i :: newelems[j] == elems[j]
            modifies newelems
        {
            newelems[i] := elems[i];
            i := i + 1;
        }
        elems := newelems;
    }

    /**
     * Insert element {e} in the queue, with resizing if needed.
     */
    method insert(e: int)
    requires ok() && elems.Length>0
    ensures ok()
    ensures size == old(size)+1 
    modifies this,elems
    {
       
        if size == elems.Length {
            resize();
            assert elems.Length > old(elems.Length);
            assert old(elems.Length) == size;
            assert elems.Length > size;
        }
        assert elems.Length > size;
        insert'(e);
    }

    /**
     * Insert element {e} in the queue, with available capacity.
     */
    method insert'(e: int)
    requires ok()
    requires size < this.elems.Length
    ensures fresh({elems} - {old(elems)})
    ensures ok()
    ensures size == old(size)+1 
    modifies this,elems
    {
        var i := size;
        elems[i] := e;
        size := size+1;
        while i > 0 && (elems[i] > elems[i-1]) 
            invariant 0 <= i 
            // Tous les éléments de i à size sont triés
            invariant forall j | i <= j < size :: this.elems[j] <= this.elems[i]
            // Tous les éléments de 0 à i-1 sont triés 
            invariant forall j,k |0<=j <= k < i  :: this.elems[j] >= this.elems[k]
            modifies elems
        {
            elems[i-1], elems[i] := elems[i], elems[i-1];
            i := i - 1;
        }
    }
}

/**
 * Tests
 */
method Main()
    requires false // TODO: remove this line
{
    var q := new PriorityQueue(2);
    q.insert(3);
    q.insert(2);
    q.insert(1);
    q.insert(2);
    assert q.abs() == multiset([1, 2, 2, 3]);
    assert is_min(1, q.abs());

    var a := q.get_min();
    var b := q.get_min();
    var c := q.get_min();
    var d := q.get_min();
    assert a <= b <= c <= d;
    assert a+b+c+d == 8;

    print "[", a, ", ", b, ", ", c, ", ", d, "]\n";
}

But I have the problem everytime, the problem is on the version 3.10.0.41215. I downgrade on the version 3.9.1.41027 and I have any problem now

**Comment by MikaelMayer** [comment] 2022-12-23 19:36
How do you interact with this file? Do you just paste the code in VSCode? On my latest version, it just says that it could not prove 4 declarations, so I don't see the problem

**Comment by benmdts** [comment] 2022-12-23 21:03
I'm trying to prove it... I'm on MacOS Ventura 13.1. I don't know if it can helps. With this version I can't see if the declarations are verified.

**Comment by keyboardDrummer** [comment] 2022-12-27 13:36
This is a recently introduced bug, which occurs simply by setting the amount of verification cores to 0 (which is also the default). This PR is a temporary fix: https://github.com/dafny-lang/ide-vscode/pull/332 with a more permanent fis here: https://github.com/dafny-lang/dafny/pull/3276

**Comment by keyboardDrummer** [comment] 2022-12-27 15:23
This is resolved in version 3.0.2 of the extension

**Closed by keyboardDrummer** 2022-12-27 15:23 UTC
Labels: bug
