### ISSUE TITLE
Every save appends the error message to the previous one in the hover text

### ISSUE THREAD

**Issue by mschlaipfer** [dafny-lang/ide-vscode#151] opened 2022-04-08 10:11 UTC
For example when running the example in https://github.com/dafny-lang/dafny/issues/1992

After saving 3 times:
![image](https://user-images.githubusercontent.com/3248425/162415281-4c905063-525a-4a59-875e-343633bd50fd.png)

One additional save:
![image](https://user-images.githubusercontent.com/3248425/162415299-6a04db89-da6e-47ec-be1e-ae7174f10918.png)

Dafny 3.5.0
VSCode extension: 2.3.0

**Comment by MikaelMayer** [comment] 2023-01-04 16:37
I can't reproduce this error in the latest versions of Dafny and extension. Obsolete errors are now marked as such and disappear at the right time. Closing it unless you can reproduce it in the latest versions.

**Closed by MikaelMayer** 2023-01-04 16:37 UTC
Labels: bug, language server
