### ISSUE TITLE
Resolution error not showing up in Problems pane

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/ide-vscode#279] opened 2022-10-10 19:43 UTC
I got into a situation where a red squiggly line is telling me there's a resolution error (which there was). Yet, the Problems pane didn't show anything.

<img width="494" alt="Screen Shot 2022-10-08 at 15 43 02" src="https://user-images.githubusercontent.com/11763367/194941084-4f28d73b-5c3c-497f-8f58-36250c6eaf42.png">

I'm afraid I don't have more information for a repro, but thought I'd nevertheless report the issue. I was using the most recent Dafny plug-in from 2 days ago.

**Comment by keyboardDrummer** [comment] 2022-10-14 11:30
Duplicate of https://github.com/dafny-lang/dafny/issues/2890

**Closed** 2022-10-14 11:30 UTC
