### ISSUE TITLE
Parenthesis color mismatch

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/ide-vscode#267] opened 2022-09-09 00:11 UTC
Parenthesis colors do not properly match in syntax like `m("[)]")`

**Comment by MikaelMayer** [comment] 2022-09-13 14:55
I don't have any problem:

![image](https://user-images.githubusercontent.com/3601079/189934816-96e2a7f7-95c3-4f30-b4d9-7b88353938c7.png)

Can you please post a screenshot?

**Comment by davidcok** [comment] 2022-09-19 11:14
<img width="221" alt="image" src="https://user-images.githubusercontent.com/5321152/191005607-91cf176e-fd23-4ae1-a9bd-31bce49d306b.png">

**Comment by davidcok** [comment] 2022-09-19 11:17
VSCode reports I'm running v2.8.2 of Dafny extension

**Comment by MikaelMayer** [comment] 2022-09-20 21:16
Weird. Can you please post the exact text? I'll try to reproduce it.

**Comment by davidcok** [comment] 2022-09-20 22:07
```
method m(s: string) {}

method t() {
  m("[)]");
}
```

**Comment by MikaelMayer** [comment] 2022-09-21 15:11
Can't reproduce, in dark and light mode.

![image](https://user-images.githubusercontent.com/3601079/191542057-2806fe16-7fae-457f-90ee-04e104a64cc1.png)

You might be using pairs of quotes that are not regular quotes in your example.

**Comment by davidcok** [comment] 2022-09-21 23:59
I did retype the quotes to check that.

**Comment by MikaelMayer** [comment] 2023-01-04 16:02
I close this issue until we find a proper repro. It might have been fixed in the meanwhile, I still can't reproduce any of it.

**Closed by MikaelMayer** 2023-01-04 16:02 UTC
