### ISSUE TITLE
Some reserved words are highlighted in strings

### ISSUE THREAD

**Issue by seebees** [dafny-lang/ide-vscode#70] opened 2021-11-02 03:56 UTC
`string` in the following code is not the same as a type.

```dafny
var tmp := "This string does not have any reserved words that should be highlighted."
```

**Comment by camrein** [comment] 2021-11-02 08:26
Thanks for reporting this issue. The root cause is that strings aren't highlighted yet. Resolving this should also fix the falsely highlighted keywords within strings.

**Closed** 2021-11-02 08:29 UTC
