### ISSUE TITLE
Generic function names not highlighted

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/ide-vscode#274] opened 2022-09-29 12:41 UTC
Dafny-VSCode highlights the name of a function in a declaration such as `function method f(t: int)`
but not in a generic declaration like `function method f<T>(t: T)`

**Comment by MikaelMayer** [comment] 2022-09-29 15:14
Can you please share a specific example? I can't reproduce the problem
![image](https://user-images.githubusercontent.com/3601079/193070503-6328eba3-59ed-4b0f-9ebb-80fe1c63ac92.png)

**Comment by MikaelMayer** [comment] 2023-01-04 15:59
Closing as we don't have  a repro for now. Feel free to reopen if you have one.

**Closed by MikaelMayer** 2023-01-04 15:59 UTC
